[package]
name = "wimon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mac_address = "1.1.5"

# for reading config from a file - put under a flag for embedded options
serde_derive = "~1.0"
serde = "~1.0"
toml = { version = "0.8.8" }
