[package]
name = "data_model"
version = "0.1.0"
edition = "2021"

[lib]
name = "data_model"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_derive = "~1.0"
serde = "~1.0"
