name = "viewr"
compatibility_date = "2024-01-22"

kv_namespaces = [
    { binding = "DEVICE_STATUS", id = "aa1793c1a3d7497bb12ce3c5d2c3f3c7" },
    { binding = "DEVICE_ID_CONNECTION_MAPPING", id = "75fde85c25c5412f8741d5ff7e61d9fd" },
    { binding = "SSID_DEVICE_STATUS", id = "61c3d5d85ca8423ca7e36e1ca411d442" },
    { binding = "SSID_LIST", id = "a2aa87ddff5541179e3fb792f0c11c22" }
]