name = "viewr"
compatibility_date = "2024-01-22"

kv_namespaces = [
    { binding = "DEVICE_STATUS", id = "aa1793c1a3d7497bb12ce3c5d2c3f3c7" },
    { binding = "CONNECTION_DEVICE_STATUS", id = "d6786cf203bf46d39ee3ec6718c27dde" },
    { binding = "DEVICE_DETAILS", id = "fb0274e0f3e7461ea6bf2322656e2fd9" }
]
