[package]
name = "pingr"
version = "0.1.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
edition = "2018"
build = "build.rs"

[[bin]]
name = "pingr"
path = "src/main.rs"

#[lib]
#name = "pingr"
#pingr = "src/lib.rs"

[dependencies]
#wifi = "0.1.0"
#wifilocation = "0.3"
#sysbar = "0.2.0"
libc = "0.2"

# Keen API integration
# https://github.com/dovahcrow/keenio-rs
#keen = "1.4.1"

[build-dependencies]
cc = "1.0"
pkg-config = "0.3"